const { chromium } = require('playwright');
const fs = require('fs');
const TARGET_REPO=process.env.TARGET_REPO||'hmtnvac-cpu/xiec', TARGET_PATH=process.env.TARGET_PATH||'data/ket_qua_1500_phim.json', TOKEN=process.env.XIEC_TOKEN;
const LIMIT=Number(process.env.STREAM2_LIMIT||10), CONCURRENCY=Number(process.env.STREAM2_CONCURRENCY||3), WAIT_MS=Number(process.env.STREAM2_WAIT_MS||12000);
if(!TOKEN) throw new Error('Missing XIEC_TOKEN');
fs.mkdirSync('stream2-debug',{recursive:true});
const H={Authorization:`Bearer ${TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'xiec-stream2-test'};
async function read(){const r=await fetch(`https://api.github.com/repos/${TARGET_REPO}/contents/${TARGET_PATH}`,{headers:H});if(!r.ok)throw new Error(`read ${r.status}`);const d=await r.json();let e=d.content||'';if(!e){const b=await fetch(`https://api.github.com/repos/${TARGET_REPO}/git/blobs/${d.sha}`,{headers:H});if(!b.ok)throw new Error(`blob ${b.status}`);e=(await b.json()).content||'';}return{sha:d.sha,movies:JSON.parse(Buffer.from(e.replace(/\n/g,''),'base64').toString('utf8'))}}
async function write(sha,movies){const r=await fetch(`https://api.github.com/repos/${TARGET_REPO}/contents/${TARGET_PATH}`,{method:'PUT',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({message:`Capture #2 final streams for ${LIMIT} newest movies`,content:Buffer.from(JSON.stringify(movies,null,2)).toString('base64'),sha,branch:'main'})});if(!r.ok)throw new Error(`write ${r.status} ${await r.text()}`)}
const isFinal=u=>/manifest|\.m3u8(?:\?|$)|\.mpd(?:\?|$)|\.vl(?:\?|$)|\.mp4(?:\?|$)|videoplayback|googlevideo/i.test(u);
const score=u=>{u=u.toLowerCase();return (u.includes('manifest')?100:0)+(u.includes('.m3u8')?90:0)+(u.includes('.mpd')?80:0)+(u.includes('.vl')?70:0)+(u.includes('videoplayback')?60:0)+(u.includes('1080')?30:0)+(u.includes('.mp4')?10:0)};
async function getEmbed(page,url){let embed='';const cap=u=>{if(/play\.vlstream\.net\/embed\/.*\/s2/i.test(u))embed=u};page.on('request',r=>cap(r.url()));page.on('response',r=>cap(r.url()));await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(1000);for(const f of page.frames()){const ok=await f.evaluate(()=>{const clean=s=>(s||'').replace(/\s+/g,' ').trim();const el=[...document.querySelectorAll('[onclick],button,a,li,[role="button"]')].find(x=>clean(x.textContent)==='#2');if(!el)return false;el.scrollIntoView({block:'center'});el.click();return true}).catch(()=>false);if(ok)break;}for(let i=0;i<24&&!embed;i++){await page.waitForTimeout(250);embed=page.frames().map(f=>f.url()).find(u=>/play\.vlstream\.net\/embed\/.*\/s2/i.test(u))||embed;}return embed;}
async function clickPlay(p,index){
  const selectors=['.jw-icon-display','.jw-display-icon-container','.jw-icon-playback','.vjs-big-play-button','button[aria-label*="Play" i]','button[title*="Play" i]','video'];
  for(const f of p.frames()) for(const s of selectors){try{const el=f.locator(s).first();if(await el.count()&&await el.isVisible({timeout:300})){await el.click({force:true,timeout:1500});console.log(`STREAM2_PLAY_CLICK ${index+1}/${LIMIT} selector=${s}`);return true;}}catch{}}
  for(const f of p.frames()){const ok=await f.evaluate(()=>{const v=document.querySelector('video');if(!v)return false;v.muted=true;v.play().catch(()=>{});v.dispatchEvent(new MouseEvent('click',{bubbles:true}));return true}).catch(()=>false);if(ok){console.log(`STREAM2_PLAY_JS ${index+1}/${LIMIT}`);return true;}}
  console.log(`STREAM2_PLAY_MISS ${index+1}/${LIMIT}`);return false;
}
async function captureFinal(ctx,embed,old,index){const p=await ctx.newPage();const bucket=new Set();const all=[];const cap=u=>{all.push(u);if(isFinal(u)&&u!==old)bucket.add(u)};p.on('request',r=>cap(r.url()));p.on('response',r=>cap(r.url()));await p.goto(embed,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(1500);await p.screenshot({path:`stream2-debug/${index+1}-before.png`,fullPage:true}).catch(()=>{});await clickPlay(p,index);await p.waitForTimeout(WAIT_MS);await p.screenshot({path:`stream2-debug/${index+1}-after.png`,fullPage:true}).catch(()=>{});for(const f of p.frames()){const vals=await f.evaluate(()=>[...document.querySelectorAll('video,source')].flatMap(el=>[el.src,el.currentSrc]).filter(Boolean)).catch(()=>[]);for(const u of vals)if(isFinal(u)&&u!==old)bucket.add(u);}const arr=[...bucket].sort((a,b)=>score(b)-score(a));if(!arr.length)console.log(`STREAM2_FINAL_REQ_SAMPLE ${index+1}/${LIMIT} ${JSON.stringify(all.slice(-20))}`);await p.close();return arr[0]||'';}
async function one(browser,m,index){const old=m.manifest_url||m.mp4_url||m.streams?.find(s=>s.name==='#1')?.url||'';const ctx=await browser.newContext({userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140 Safari/537.36',viewport:{width:1365,height:768}});const p=await ctx.newPage();try{const embed=await getEmbed(p,m.page_url);if(!embed){console.log(`STREAM2_NO_EMBED ${index+1}/${LIMIT} id=${m.id}`);return{...m,stream2_status:'no_s2_embed'}}console.log(`STREAM2_EMBED ${index+1}/${LIMIT} id=${m.id} url=${embed}`);const final=await captureFinal(ctx,embed,old,index);if(!final){console.log(`STREAM2_NO_FINAL ${index+1}/${LIMIT} id=${m.id}`);return{...m,stream2_status:'s2_no_final',stream2_embed:embed}}const streams=[];if(old)streams.push({name:'#1',url:old});streams.push({name:'#2',url:final});console.log(`STREAM2_OK ${index+1}/${LIMIT} id=${m.id} url=${final}`);return{...m,streams,stream2_embed:embed,stream2_status:'ok'};}catch(e){console.log(`STREAM2_ERR ${index+1}/${LIMIT} id=${m.id} error=${e.message}`);return{...m,stream2_status:`error:${e.message}`}}finally{await p.close().catch(()=>{});await ctx.close().catch(()=>{})}}
(async()=>{let{sha,movies}=await read();const targets=movies.map((m,i)=>({m,i})).filter(x=>x.m.page_url).slice(0,LIMIT);const browser=await chromium.launch({headless:false,args:['--autoplay-policy=no-user-gesture-required']});let cursor=0,done=0,ok=0;async function worker(){while(true){const n=cursor++;if(n>=targets.length)return;const t=targets[n],out=await one(browser,t.m,n);movies[t.i]=out;done++;if(out.stream2_status==='ok')ok++;console.log(`STREAM2_PROGRESS processed=${done}/${targets.length} found=${ok} missed=${done-ok}`)}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,targets.length)},worker));await browser.close();await write(sha,movies);console.log(`STREAM2_TEST_DONE tested=${targets.length} found=${ok} failed=${targets.length-ok}`)})();