const { chromium } = require('playwright');
const TARGET_REPO=process.env.TARGET_REPO||'hmtnvac-cpu/xiec',TARGET_PATH=process.env.TARGET_PATH||'data/ket_qua_1500_phim.json',TOKEN=process.env.XIEC_TOKEN;
const LIMIT=Number(process.env.STREAM1_LIMIT||10),CONCURRENCY=Number(process.env.STREAM1_CONCURRENCY||5);
if(!TOKEN)throw new Error('Missing XIEC_TOKEN');
const H={Authorization:`Bearer ${TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'xiec-stream1-test'};
async function read(){const r=await fetch(`https://api.github.com/repos/${TARGET_REPO}/contents/${TARGET_PATH}`,{headers:H});if(!r.ok)throw new Error(`read ${r.status}`);const d=await r.json();let e=d.content||'';if(!e){const b=await fetch(`https://api.github.com/repos/${TARGET_REPO}/git/blobs/${d.sha}`,{headers:H});if(!b.ok)throw new Error(`blob ${b.status}`);e=(await b.json()).content||''}return{sha:d.sha,movies:JSON.parse(Buffer.from(e.replace(/\n/g,''),'base64').toString())}}
async function write(sha,movies){const r=await fetch(`https://api.github.com/repos/${TARGET_REPO}/contents/${TARGET_PATH}`,{method:'PUT',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({message:`Pilot direct #1 extraction for ${LIMIT} movies`,content:Buffer.from(JSON.stringify(movies,null,2)).toString('base64'),sha,branch:'main'})});if(!r.ok)throw new Error(`write ${r.status} ${await r.text()}`)}
function extractFile(html){const src=html.match(/window\.__SRC\s*=\s*(\[[\s\S]*?\])\s*;/i);if(src){try{const arr=JSON.parse(src[1]);const file=arr?.find(x=>x&&typeof x.file==='string')?.file;if(file)return file}catch{}}const m=html.match(/["']file["']\s*:\s*["'](https?:\/\/[^"']+)["']/i)||html.match(/file\s*:\s*["'](https?:\/\/[^"']+)["']/i);return m?m[1].replace(/\\\//g,'/').replace(/&amp;/g,'&'):''}
async function getS1Embed(page,url){let embed='';const cap=u=>{if(/play\.vlstream\.net\/embed\/.*\/s1/i.test(u))embed=u};page.on('request',r=>cap(r.url()));page.on('response',r=>cap(r.url()));await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});for(let i=0;i<16&&!embed;i++){await page.waitForTimeout(250);embed=page.frames().map(f=>f.url()).find(u=>/play\.vlstream\.net\/embed\/.*\/s1/i.test(u))||embed}if(embed)return embed;for(const f of page.frames()){const hrefs=await f.locator('iframe[src],a[href]').evaluateAll(els=>els.map(e=>e.src||e.href).filter(Boolean)).catch(()=>[]);embed=hrefs.find(u=>/play\.vlstream\.net\/embed\/.*\/s1/i.test(u))||embed;if(embed)break}return embed}
async function one(browser,m,index,total){const ctx=await browser.newContext({userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140 Safari/537.36'}),p=await ctx.newPage();try{const embed=await getS1Embed(p,m.page_url);if(!embed){console.log(`STREAM1_NO_EMBED ${index+1}/${total} id=${m.id}`);return{...m,stream1_test:'no_embed'}}const r=await fetch(embed,{headers:{'User-Agent':'Mozilla/5.0','Referer':'https://vlxx.phd/'},redirect:'follow'});const html=await r.text();const file=extractFile(html);if(!file||!/\/manifest-s1\//i.test(file)){console.log(`STREAM1_INVALID ${index+1}/${total} id=${m.id} file=${file||'NONE'}`);return{...m,stream1_test:'invalid'}}console.log(`STREAM1_OK ${index+1}/${total} id=${m.id} url=${file}`);const current=m.manifest_url||'';const same=current===file;return{...m,stream1_direct:file,stream1_test:same?'match_existing':'different_from_existing'};}catch(e){console.log(`STREAM1_ERR ${index+1}/${total} id=${m.id} error=${e.message}`);return{...m,stream1_test:`error:${e.message}`}}finally{await ctx.close()}}
(async()=>{let{sha,movies}=await read();const t=movies.map((m,i)=>({m,i})).filter(x=>x.m.page_url).slice(0,LIMIT);const b=await chromium.launch({headless:true});let c=0,done=0,ok=0,match=0;async function w(){while(1){const n=c++;if(n>=t.length)return;const x=t[n],o=await one(b,x.m,n,t.length);movies[x.i]=o;done++;if(o.stream1_direct)ok++;if(o.stream1_test==='match_existing')match++;console.log(`STREAM1_PROGRESS processed=${done}/${t.length} found=${ok} match_existing=${match}`)}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,t.length)},w));await b.close();await write(sha,movies);console.log(`STREAM1_TEST_DONE tested=${t.length} found=${ok} matched=${match}`)})();