const { chromium } = require('playwright');
const fs=require('fs');
const TARGET_REPO=process.env.TARGET_REPO||'hmtnvac-cpu/xiec',TARGET_PATH=process.env.TARGET_PATH||'data/ket_qua_1500_phim.json',TOKEN=process.env.XIEC_TOKEN;
const LIMIT=Number(process.env.STREAM2_LIMIT||99999),CONCURRENCY=Number(process.env.STREAM2_CONCURRENCY||8);
if(!TOKEN)throw new Error('Missing XIEC_TOKEN');fs.mkdirSync('stream2-debug',{recursive:true});
const H={Authorization:`Bearer ${TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'xiec-stream2-source'};
async function read(){const r=await fetch(`https://api.github.com/repos/${TARGET_REPO}/contents/${TARGET_PATH}`,{headers:H});if(!r.ok)throw new Error(`read ${r.status}`);const d=await r.json();let e=d.content||'';if(!e){const b=await fetch(`https://api.github.com/repos/${TARGET_REPO}/git/blobs/${d.sha}`,{headers:H});if(!b.ok)throw new Error(`blob ${b.status}`);e=(await b.json()).content||''}return{sha:d.sha,movies:JSON.parse(Buffer.from(e.replace(/\n/g,''),'base64').toString())}}
async function write(sha,movies){const r=await fetch(`https://api.github.com/repos/${TARGET_REPO}/contents/${TARGET_PATH}`,{method:'PUT',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({message:'Capture missing #2 streams',content:Buffer.from(JSON.stringify(movies,null,2)).toString('base64'),sha,branch:'main'})});if(!r.ok)throw new Error(`write ${r.status} ${await r.text()}`)}
const has2=m=>Array.isArray(m.streams)&&m.streams.some(s=>s?.name==='#2'&&typeof s.url==='string'&&/\/manifest-s2\//i.test(s.url));
async function getEmbed(p,url){let embed='';const cap=u=>{if(/play\.vlstream\.net\/embed\/.*\/s2/i.test(u))embed=u};p.on('request',r=>cap(r.url()));await p.goto(url,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(700);for(const f of p.frames()){const ok=await f.evaluate(()=>{const c=s=>(s||'').replace(/\s+/g,' ').trim();const e=[...document.querySelectorAll('[onclick],button,a,li,[role=button]')].find(x=>c(x.textContent)==='#2');if(!e)return false;e.click();return true}).catch(()=>false);if(ok)break}for(let i=0;i<20&&!embed;i++){await p.waitForTimeout(250);embed=p.frames().map(f=>f.url()).find(u=>/play\.vlstream\.net\/embed\/.*\/s2/i.test(u))||embed}return embed}
function extractFile(html){const src=html.match(/window\.__SRC\s*=\s*(\[[\s\S]*?\])\s*;/i);if(src){try{const arr=JSON.parse(src[1]);const file=arr?.find(x=>x&&typeof x.file==='string')?.file;if(file)return file}catch(e){console.log(`STREAM2_SRC_JSON_ERR ${e.message}`)}}const m=html.match(/["']file["']\s*:\s*["'](https?:\/\/[^"']+)["']/i)||html.match(/file\s*:\s*["'](https?:\/\/[^"']+)["']/i);return m?m[1].replace(/\\\//g,'/').replace(/&amp;/g,'&'):''}
async function inspect(embed,index,total){const res=await fetch(embed,{headers:{'User-Agent':'Mozilla/5.0','Referer':'https://vlxx.phd/'},redirect:'follow'});const html=await res.text();const file=extractFile(html);console.log(`STREAM2_SOURCE ${index+1}/${total} http=${res.status} file=${file||'NONE'}`);return file}
async function one(browser,m,index,total){const ctx=await browser.newContext({userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140 Safari/537.36'}),p=await ctx.newPage();try{const embed=await getEmbed(p,m.page_url);if(!embed){console.log(`STREAM2_NO_EMBED ${index+1}/${total} id=${m.id}`);return{...m,stream2_status:'no_s2_embed'}}const file=await inspect(embed,index,total);if(!file||!/\/manifest-s2\//i.test(file)){console.log(`STREAM2_INVALID ${index+1}/${total} id=${m.id}`);return{...m,stream2_embed:embed,stream2_status:'invalid_s2'}}const old=m.manifest_url||m.mp4_url||m.streams?.find(s=>s.name==='#1')?.url||'';const streams=[];if(old)streams.push({name:'#1',url:old});streams.push({name:'#2',url:file});console.log(`STREAM2_OK ${index+1}/${total} id=${m.id} url=${file}`);return{...m,streams,stream2_embed:embed,stream2_status:'ok'};}catch(e){console.log(`STREAM2_ERR ${index+1}/${total} id=${m.id} error=${e.message}`);return{...m,stream2_status:`error:${e.message}`}}finally{await ctx.close()}}
(async()=>{let{sha,movies}=await read();const pending=movies.map((m,i)=>({m,i})).filter(x=>x.m.page_url&&!has2(x.m)).slice(0,LIMIT);console.log(`STREAM2_START total_movies=${movies.length} already_have=${movies.filter(has2).length} pending=${pending.length} concurrency=${CONCURRENCY}`);if(!pending.length){console.log('STREAM2_DONE nothing_to_do');return}const b=await chromium.launch({headless:true});let c=0,done=0,ok=0;async function w(){while(1){const n=c++;if(n>=pending.length)return;const x=pending[n],o=await one(b,x.m,n,pending.length);movies[x.i]=o;done++;if(o.stream2_status==='ok')ok++;if(done%10===0||done===pending.length)console.log(`STREAM2_PROGRESS processed=${done}/${pending.length} found=${ok} missed=${done-ok}`)}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,pending.length)},w));await b.close();if(ok>0)await write(sha,movies);console.log(`STREAM2_TEST_DONE tested=${pending.length} found=${ok} failed=${pending.length-ok}`)})();