const { chromium } = require('playwright');
const TARGET_REPO=process.env.TARGET_REPO||'hmtnvac-cpu/xiec', TARGET_PATH=process.env.TARGET_PATH||'data/ket_qua_1500_phim.json', TOKEN=process.env.XIEC_TOKEN;
const LIMIT=Number(process.env.STREAM2_LIMIT||10), CONCURRENCY=Number(process.env.STREAM2_CONCURRENCY||10);
const WAIT_MS=Number(process.env.STREAM2_WAIT_MS||8000);
if(!TOKEN) throw new Error('Missing XIEC_TOKEN');
const H={Authorization:`Bearer ${TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'xiec-stream2-test'};
async function read(){const r=await fetch(`https://api.github.com/repos/${TARGET_REPO}/contents/${TARGET_PATH}`,{headers:H});if(!r.ok)throw new Error(`read ${r.status}`);const d=await r.json();let encoded=d.content||'';if(!encoded){const b=await fetch(`https://api.github.com/repos/${TARGET_REPO}/git/blobs/${d.sha}`,{headers:H});if(!b.ok)throw new Error(`blob ${b.status}`);encoded=(await b.json()).content||'';}return{sha:d.sha,movies:JSON.parse(Buffer.from(encoded.replace(/\n/g,''),'base64').toString('utf8'))}}
async function write(sha,movies){const r=await fetch(`https://api.github.com/repos/${TARGET_REPO}/contents/${TARGET_PATH}`,{method:'PUT',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({message:`Capture #2 final streams for ${LIMIT} newest movies`,content:Buffer.from(JSON.stringify(movies,null,2)).toString('base64'),sha,branch:'main'})});if(!r.ok)throw new Error(`write ${r.status} ${await r.text()}`)}
const isFinal=u=>/manifest|\.m3u8(?:\?|$)|\.mpd(?:\?|$)|\.vl(?:\?|$)|\.mp4(?:\?|$)|videoplayback|googlevideo/i.test(u);
const score=u=>{u=u.toLowerCase();return (u.includes('manifest')?100:0)+(u.includes('.m3u8')?90:0)+(u.includes('.mpd')?80:0)+(u.includes('.vl')?70:0)+(u.includes('videoplayback')?60:0)+(u.includes('1080')?30:0)+(u.includes('.mp4')?10:0)};
async function activateAndGetEmbed(page){let embed='';const seen=new Set();const cap=u=>{seen.add(u);if(/play\.vlstream\.net\/embed\/.*\/s2/i.test(u)) embed=u};page.on('request',r=>cap(r.url()));page.on('response',r=>cap(r.url()));await page.goto(page._xiecUrl,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(700);for(const f of page.frames()){const ok=await f.evaluate(()=>{const clean=s=>(s||'').replace(/\s+/g,' ').trim();const els=[...document.querySelectorAll('button,a,[role="button"],li,span,div,[onclick]')].filter(el=>clean(el.textContent)==='#2');if(!els.length)return false;const el=els[0].closest('[onclick],button,a,[role="button"],li')||els[0];try{el.click();}catch{};return true}).catch(()=>false);if(ok)break;}for(let i=0;i<20&&!embed;i++){await page.waitForTimeout(250);const frames=page.frames().map(f=>f.url()).filter(Boolean);embed=frames.find(u=>/play\.vlstream\.net\/embed\/.*\/s2/i.test(u))||embed;}return embed;}
async function captureFinal(context,embed,old){const p=await context.newPage();const bucket=new Set();const cap=u=>{if(isFinal(u)&&u!==old)bucket.add(u)};p.on('request',r=>cap(r.url()));p.on('response',r=>cap(r.url()));await p.route('**/*',r=>['image','font'].includes(r.request().resourceType())?r.abort():r.continue());try{await p.goto(embed,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(WAIT_MS);for(const f of p.frames()){const vals=await f.evaluate(()=>{const out=[];for(const el of document.querySelectorAll('video,source')){if(el.src)out.push(el.src);if(el.currentSrc)out.push(el.currentSrc)}return out}).catch(()=>[]);for(const u of vals)if(isFinal(u)&&u!==old)bucket.add(u);}const arr=[...bucket].sort((a,b)=>score(b)-score(a));return arr[0]||'';}finally{await p.close();}}
async function one(browser,m,index){const old=m.manifest_url||m.mp4_url||m.streams?.find(s=>s.name==='#1')?.url||'';const ctx=await browser.newContext({userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140 Safari/537.36',viewport:{width:1280,height:720}});const p=await ctx.newPage();p._xiecUrl=m.page_url;try{const embed=await activateAndGetEmbed(p);if(!embed){console.log(`STREAM2_NO_EMBED ${index+1}/${LIMIT} id=${m.id}`);return{...m,stream2_status:'no_s2_embed'}}console.log(`STREAM2_EMBED ${index+1}/${LIMIT} id=${m.id} url=${embed}`);const final=await captureFinal(ctx,embed,old);if(!final){console.log(`STREAM2_NO_FINAL ${index+1}/${LIMIT} id=${m.id}`);return{...m,stream2_status:'s2_no_final',stream2_embed:embed}}const streams=[];if(old)streams.push({name:'#1',url:old});streams.push({name:'#2',url:final});console.log(`STREAM2_OK ${index+1}/${LIMIT} id=${m.id} url=${final}`);return{...m,streams,stream2_embed:embed,stream2_status:'ok'};}catch(e){console.log(`STREAM2_ERR ${index+1}/${LIMIT} id=${m.id} error=${e.message}`);return{...m,stream2_status:`error:${e.message}`}}finally{await p.close().catch(()=>{});await ctx.close().catch(()=>{})}}
(async()=>{let{sha,movies}=await read();const targets=movies.map((m,i)=>({m,i})).filter(x=>x.m.page_url).slice(0,LIMIT);const browser=await chromium.launch({headless:true});let cursor=0,done=0,ok=0;async function worker(){while(true){const n=cursor++;if(n>=targets.length)return;const t=targets[n];const out=await one(browser,t.m,n);movies[t.i]=out;done++;if(out.stream2_status==='ok')ok++;console.log(`STREAM2_PROGRESS processed=${done}/${targets.length} found=${ok} missed=${done-ok}`)}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,targets.length)},worker));await browser.close();await write(sha,movies);console.log(`STREAM2_TEST_DONE tested=${targets.length} found=${ok} failed=${targets.length-ok}`)})();